# Generated by Django 3.2.8 on 2021-10-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211022_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='main.resume'),
        ),
        migrations.AlterField(
            model_name='social',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='main.profile'),
        ),
        migrations.AlterField(
            model_name='work',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='main.resume'),
        ),
    ]
