# Generated by Django 3.2.8 on 2021-10-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211022_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-id']},
        ),
    ]
