# Generated by Django 3.2.8 on 2022-01-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(help_text='Describe yourself', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_download',
            field=models.URLField(blank=True, help_text='A link to download your resume from', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='class_name',
            field=models.CharField(choices=[('fa fa-facebook', 'Facebook Icon'), ('fa fa-twitter', 'Twitter Icon'), ('fa fa-instagram', 'Instagram Icon'), ('fa fa-whatsapp', 'Whatsapp Icon'), ('fa fa-linkedin', 'LinkedIn Icon'), ('fa fa-github', 'Github Icon')], max_length=20),
        ),
    ]
