# Generated by Django 3.2.8 on 2024-03-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220121_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='class_name',
            field=models.CharField(choices=[('fa fa-facebook', 'Facebook Icon'), ('fa fa-twitter', 'Twitter Icon'), ('fa fa-instagram', 'Instagram Icon'), ('fa fa-whatsapp', 'Whatsapp Icon'), ('fa fa-linkedin', 'LinkedIn Icon'), ('fa fa-github', 'Github Icon'), ('fa-brands fa-tiktok', 'TikTok Icon')], help_text='Icon to represent your social', max_length=20),
        ),
    ]
